### PR TITLE
Fixed a bug of window-selector freeze due to incorrect modulo calculation

### PR DESCRIPTION
**Pull request by daizeng1984**
Hi Kai, 

I really love your phoenix config. Very close to a fuzzy finder I was looking for. Thank you for making and share them. 

Here I just find a tiny bug that freeze phoenix with a one-liner fix PR.

Thanks,
Zeng

### CODE REVIEW

**Comment by kgrossjo** [comment]
Hi Zeng,

this is really cool, thanks a lot for your contribution.  If I understand correctly, the problem happens when `this.selectedWindow` is 0.  Because then `-1 + this.selectedWindow` is -1.  And maybe -1 modulo number of windows is also -1.

But we want numbers between 0 and the number of windows.  So if you add the number of windows, then -1 becomes number of windows minus one.

Is my understanding correct?

(Unfortunately, I stopped using Phoenix because I got more ambitious and wanted to send keystrokes to the applications.  I wanted to implement a vi-like mode.  So I thought and thought and then finally I switched to Hammerspoon.  So I won't test this in my regular usage.)

Kai

**Comment by kgrossjo** [comment]
It just occurred to me: since I don't use this anymore, maybe I could point folks to your copy of this so that they might get further updates in the future?  Would you mind if I added a link to your work?  (What would the URL be?)

**Comment by daizeng1984** [comment]
Hi Kai,

Yes Javascript has different modulo than some other language and -1 %
nwindows is -1.

I took a quick look at the Hammerspoon. It seems to be even cooler!!!

No problem. You can point a link to my repo. All fine for me.

Thanks!

Zeng

**Comment by kgrossjo** [comment]
Thank you very much, I've now done so.

**Comment by daizeng1984** [comment]
cool! 😀

**Pull request merged**
